// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLiY9d_U2V5T96mnPZ-DScnIN7m2yMbBU',
    appId: '1:431314151698:web:c1df01a89d354f0338ebcb',
    messagingSenderId: '431314151698',
    projectId: 'bank-mitra-unique',
    authDomain: 'bank-mitra-unique.firebaseapp.com',
    storageBucket: 'bank-mitra-unique.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBncaV1KYHlbRc1UnPSdlafT2GHnlv-7DQ',
    appId: '1:431314151698:android:b3bd3b80b522811b38ebcb',
    messagingSenderId: '431314151698',
    projectId: 'bank-mitra-unique',
    storageBucket: 'bank-mitra-unique.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKQ1VAX5uIDzX4payeRro4hfsrRQwK_Ls',
    appId: '1:431314151698:ios:64443f562493308038ebcb',
    messagingSenderId: '431314151698',
    projectId: 'bank-mitra-unique',
    storageBucket: 'bank-mitra-unique.appspot.com',
    androidClientId: '431314151698-4s0qahbmbsfre911o14doo2qkbrne7l6.apps.googleusercontent.com',
    iosClientId: '431314151698-7sfa39purhpd1o37nh6s7vl612h0ctld.apps.googleusercontent.com',
    iosBundleId: 'com.example.bankSathi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKQ1VAX5uIDzX4payeRro4hfsrRQwK_Ls',
    appId: '1:431314151698:ios:64443f562493308038ebcb',
    messagingSenderId: '431314151698',
    projectId: 'bank-mitra-unique',
    storageBucket: 'bank-mitra-unique.appspot.com',
    androidClientId: '431314151698-4s0qahbmbsfre911o14doo2qkbrne7l6.apps.googleusercontent.com',
    iosClientId: '431314151698-7sfa39purhpd1o37nh6s7vl612h0ctld.apps.googleusercontent.com',
    iosBundleId: 'com.example.bankSathi',
  );
}
